modLoader="javafml"
loaderVersion="[37,)"
license="Academic Free License v3.0"

[[mods]]
modId="wingsoffireweapons"
version="1.0.0"
displayName="WIngsOfFireWeapons"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Justi, MCreator"

[[dependencies.wingsoffireweapons]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1]"
    ordering="NONE"
    side="BOTH"




